field: 1f3041b9-77c0-4580-ad2e-f114e03902b9 # Nav Links
fieldLayouts:
  bc1dec41-21fb-4efb-a1d7-6b4804d13d0d:
    tabs:
      -
        elements:
          -
            fieldUid: 8e3fb60c-aba2-4966-8c5d-939ad13044a5 # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c299b020-3601-4a71-bfbe-5d5a8a17996c # Link Destination
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b52a04a6-f337-4ba1-b627-808750867661 # Test
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8e3fb60c-aba2-4966-8c5d-939ad13044a5: # Link Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: ''
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b52a04a6-f337-4ba1-b627-808750867661: # Test
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: test
    instructions: ''
    name: Test
    searchable: false
    settings:
      contentTable: '{{%stc_2_test}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  c299b020-3601-4a71-bfbe-5d5a8a17996c: # Link Destination
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkDestination
    instructions: ''
    name: 'Link Destination'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Select a page'
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: links
name: Link
sortOrder: 1
