columnSuffix: null
contentColumnType: string
fieldGroup: 2a24854f-77e9-44a6-8ca3-c715328f5924 # Home Page
handle: heroImage
instructions: ''
name: 'Hero Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:e484cb54-49c9-4f80-8ded-d769de4786f2' # Uploads
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add background Image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:e484cb54-49c9-4f80-8ded-d769de4786f2' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:e484cb54-49c9-4f80-8ded-d769de4786f2' # Uploads
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
