contentColumnType: string
fieldGroup: 2a24854f-77e9-44a6-8ca3-c715328f5924 # Home Page
handle: testimonies
instructions: ''
name: Testimonies
searchable: false
settings:
  contentTable: '{{%matrixcontent_testimonies}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
