defaultPlacement: end
enableVersioning: true
handle: productListingPage
name: 'Product Listing Page'
propagationMethod: all
siteSettings:
  e92c1b76-66ef-415c-9b13-f7b5b74aa8d4: # BEST International
    enabledByDefault: true
    hasUrls: true
    template: products\index
    uriFormat: products
type: single
