defaultPlacement: end
enableVersioning: true
handle: products
name: Products
propagationMethod: all
siteSettings:
  e92c1b76-66ef-415c-9b13-f7b5b74aa8d4: # BEST International
    enabledByDefault: true
    hasUrls: true
    template: products\_entry
    uriFormat: 'products/{slug}'
structure:
  maxLevels: null
  uid: 3e8dd6a8-1e94-4f02-8508-53c083e37564
type: structure
